name: continuos integration
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
env:
  ## Sets environment variable
  ARTIFACTORY_USER: ${{ secrets.JFROG_USER }}
  ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
jobs:
  gradle-build:
    name: Gradle build
    runs-on: [self-hosted]
    container:
      image: gradle:jdk17
    steps:
    - name: Check out commit
      uses: actions/checkout@v2
    - name: Build
      run: |
        gradle build --refresh-dependencies --info
