name: continuos integration
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
      
jobs:
  gradle-build:
    name: Gradle build
    runs-on: [self-hosted]
    container:
      image: gradle:jdk17
    steps:
    - name: Check out commit
      uses: actions/checkout@v2
    - name: Wrapper
      run: |
        gradle wrapper
      env:
        ARTIFACTORY_USER: ${{ secrets.JFROG_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    - name: Build
      run: |
        ./gradlew build
      env:
        ARTIFACTORY_USER: ${{ secrets.JFROG_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    ##- name: Publish
    ##  run: |
    ##    gradle artifactoryPublish
    ##  env:
    ##    ARTIFACTORY_USER: ${{ secrets.JFROG_USER }}
    ##    ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
